### ISSUE TITLE
Databehandleraftale tillæg

### ISSUE THREAD

**Issue by tna-randers** [Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi#97]
Der skal udarbejdes et tillæg til databehandleraftalen.

**Comment by cbh-randers** [comment]
@st-randers Kan du muligvis selv udfylde den her? Jeg ved faktisk ikke særlig meget om, hvad robotten rent faktisk gør (eller også har jeg glemt det - barselshjerne 😄 ), eller hvilke data den behandler? Eller kan jeg finde beskrivelser af det nogle steder?

Vi kan også tage en snak om det, hvor du fortæller mig det, men så kan du ligeså godt udfylde den tænker.
